### ISSUE TITLE
data set link is not working

### ISSUE THREAD

**Issue by MohaiminDev** [DPBayes/dp-representation-transfer#1]
Hi,
I was trying to study your code to learning about differential privacy. But, The link "https://dl.dropboxusercontent.com/u/11929126/sanger1018_brainarray_ensemblgene_rma.txt.gz" for gene expressions: "Expression|Preprocessed|Cell lines|RMA normalised expression data for Cell lines".

Can you please give me an idea how to get the data?

Looking forward to hear from you.

**Comment by mixheikk** [comment]
Hi, you should still be able to find the correct version from GDSC past releases. From a quick glance this looks like it should be the one ftp://ftp.sanger.ac.uk/pub4/cancerrxgene/releases/release-6.0/
Will need to check this with more time at some point.
